---

helm_version: 2.9.1
helm_url: https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz
helm_archive: /tmp/helm_{{ helm_version }}.zip
helm_unarchive: /tmp/helm_{{ helm_version }}
helm_bin: /usr/local/bin/helm
