---

- name: check if installed
  command: dpkg-query -s atom
  register: dpkg_check
  failed_when: dpkg_check.rc > 1

- name: install
  apt:
    deb: https://atom.io/download/deb
    state: present
  when: dpkg_check.rc == 1
